# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.user import User  # noqa: F401,E501
import util


class Approval(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user: User=None, _datetime: datetime=None, approval_degree: float=None):  # noqa: E501
        """Approval - a model defined in Swagger

        :param user: The user of this Approval.  # noqa: E501
        :type user: User
        :param _datetime: The _datetime of this Approval.  # noqa: E501
        :type _datetime: datetime
        :param approval_degree: The approval_degree of this Approval.  # noqa: E501
        :type approval_degree: float
        """
        self.swagger_types = {
            'user': User,
            '_datetime': datetime,
            'approval_degree': float
        }

        self.attribute_map = {
            'user': 'user',
            '_datetime': 'datetime',
            'approval_degree': 'approval_degree'
        }
        self._user = user
        self.__datetime = _datetime
        self._approval_degree = approval_degree

    @classmethod
    def from_dict(cls, dikt) -> 'Approval':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Approval of this Approval.  # noqa: E501
        :rtype: Approval
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this Approval.


        :return: The user of this Approval.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this Approval.


        :param user: The user of this Approval.
        :type user: User
        """

        self._user = user

    @property
    def _datetime(self) -> datetime:
        """Gets the _datetime of this Approval.


        :return: The _datetime of this Approval.
        :rtype: datetime
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: datetime):
        """Sets the _datetime of this Approval.


        :param _datetime: The _datetime of this Approval.
        :type _datetime: datetime
        """

        self.__datetime = _datetime

    @property
    def approval_degree(self) -> float:
        """Gets the approval_degree of this Approval.


        :return: The approval_degree of this Approval.
        :rtype: float
        """
        return self._approval_degree

    @approval_degree.setter
    def approval_degree(self, approval_degree: float):
        """Sets the approval_degree of this Approval.


        :param approval_degree: The approval_degree of this Approval.
        :type approval_degree: float
        """

        self._approval_degree = approval_degree
