# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class Links(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, _datetime: datetime=None, description: str=None):  # noqa: E501
        """Links - a model defined in Swagger

        :param url: The url of this Links.  # noqa: E501
        :type url: str
        :param _datetime: The _datetime of this Links.  # noqa: E501
        :type _datetime: datetime
        :param description: The description of this Links.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'url': str,
            '_datetime': datetime,
            'description': str
        }

        self.attribute_map = {
            'url': 'url',
            '_datetime': 'datetime',
            'description': 'description'
        }
        self._url = url
        self.__datetime = _datetime
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Links':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Links of this Links.  # noqa: E501
        :rtype: Links
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Links.


        :return: The url of this Links.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Links.


        :param url: The url of this Links.
        :type url: str
        """

        self._url = url

    @property
    def _datetime(self) -> datetime:
        """Gets the _datetime of this Links.


        :return: The _datetime of this Links.
        :rtype: datetime
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: datetime):
        """Sets the _datetime of this Links.


        :param _datetime: The _datetime of this Links.
        :type _datetime: datetime
        """

        self.__datetime = _datetime

    @property
    def description(self) -> str:
        """Gets the description of this Links.


        :return: The description of this Links.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Links.


        :param description: The description of this Links.
        :type description: str
        """

        self._description = description
