# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.argument import Argument  # noqa: F401,E501
import util


class Option(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, argument: Argument=None):  # noqa: E501
        """Option - a model defined in Swagger

        :param argument: The argument of this Option.  # noqa: E501
        :type argument: Argument
        """
        self.swagger_types = {
            'argument': Argument
        }

        self.attribute_map = {
            'argument': 'argument'
        }
        self._argument = argument

    @classmethod
    def from_dict(cls, dikt) -> 'Option':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Option of this Option.  # noqa: E501
        :rtype: Option
        """
        return util.deserialize_model(dikt, cls)

    @property
    def argument(self) -> Argument:
        """Gets the argument of this Option.


        :return: The argument of this Option.
        :rtype: Argument
        """
        return self._argument

    @argument.setter
    def argument(self, argument: Argument):
        """Sets the argument of this Option.


        :param argument: The argument of this Option.
        :type argument: Argument
        """

        self._argument = argument
