# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.argument import Argument  # noqa: F401,E501
from swagger_server import util


class Topic(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, arguments: Argument=None):  # noqa: E501
        """Topic - a model defined in Swagger

        :param arguments: The arguments of this Topic.  # noqa: E501
        :type arguments: Argument
        """
        self.swagger_types = {
            'arguments': Argument
        }

        self.attribute_map = {
            'arguments': 'arguments'
        }
        self._arguments = arguments

    @classmethod
    def from_dict(cls, dikt) -> 'Topic':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Topic of this Topic.  # noqa: E501
        :rtype: Topic
        """
        return util.deserialize_model(dikt, cls)

    @property
    def arguments(self) -> Argument:
        """Gets the arguments of this Topic.


        :return: The arguments of this Topic.
        :rtype: Argument
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments: Argument):
        """Sets the arguments of this Topic.


        :param arguments: The arguments of this Topic.
        :type arguments: Argument
        """

        self._arguments = arguments
