# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, email: str=None, birthday: datetime=None):  # noqa: E501
        """User - a model defined in Swagger

        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param birthday: The birthday of this User.  # noqa: E501
        :type birthday: datetime
        """
        self.swagger_types = {
            'name': str,
            'email': str,
            'birthday': datetime
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'birthday': 'birthday'
        }
        self._name = name
        self._email = email
        self._birthday = birthday

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this User.


        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.


        :param name: The name of this User.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def birthday(self) -> datetime:
        """Gets the birthday of this User.


        :return: The birthday of this User.
        :rtype: datetime
        """
        return self._birthday

    @birthday.setter
    def birthday(self, birthday: datetime):
        """Sets the birthday of this User.


        :param birthday: The birthday of this User.
        :type birthday: datetime
        """

        self._birthday = birthday
